CREATE TABLE RentalBookings (
    BookingId INTEGER PRIMARY KEY AUTOINCREMENT,
    FullName TEXT NOT NULL,
    Email TEXT NOT NULL,
    Phone TEXT NOT NULL,
    CarCategory TEXT NOT NULL,
    CarName TEXT NOT NULL,
    Transmission TEXT NOT NULL,
    FuelType TEXT NOT NULL,
    Passengers INTEGER NOT NULL,
    PickupLocation TEXT NOT NULL,
    RentalDate TEXT NOT NULL,
    ReturnDate TEXT NOT NULL,
    PickupTime TEXT NOT NULL,
    DrivingType TEXT NOT NULL,
    Insurance TEXT NOT NULL,
    GPS INTEGER NOT NULL DEFAULT 0,
    ChildSeat INTEGER NOT NULL DEFAULT 0,
    AdditionalDriver INTEGER NOT NULL DEFAULT 0,
    AdditionalRequirements TEXT NULL,
    RentalDays INTEGER NOT NULL,
    DailyRate REAL NOT NULL,
    TotalAmount REAL NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
